### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by hyusetiawan** [tanchongmin/strictjson#1]
it's such a common use case to generate json or other structured response, perhaps it's better to instead wrap this into a library? albeit just one function call but then it contains more logic than the infamous [left pad](https://www.theverge.com/2016/3/24/11300840/how-an-irate-developer-briefly-broke-javascript) :)

**Comment by tanchongmin** [comment]
Thanks for the suggestion. I will do up a library after I finish up on Functions and Agents for this repo:)

**Comment by hyusetiawan** [comment]
@tanchongmin  I would also suggest for the output format to use JSON schema instead, at the expense of more tokens but gpt based llms seem to be very familiar with the output

**Comment by tanchongmin** [comment]
with strict_text (Strict JSON v2), we can now get nested outputs!

**Comment by tanchongmin** [comment]
Nested output formats of multiple lists and dictionaries are now supported with StrictJSON v2.2.0. You can even do type checking for various output fields! Check it out!
