### ISSUE TITLE
Adjust a regular expression

### ISSUE THREAD

**Issue by dahua966** [tanchongmin/strictjson#14]
First of all, thanks for sharing the code.

In the `strictjson/base.py`, line 40
```python
38  # if all is good, we then extract out the fields
39  # Use regular expressions to extract keys and values
40  pattern = fr",*\s*['|\"]{delimiter}([^#]*){delimiter}['|\"]: "
```
The regular expression ends with a space symbol.
However, sometimes LLM generates dictionary strings without Spaces after the colon.
For example: `{"###name###":"Bob"}`

The `pattern` can be changed to `fr",*\s*['|\"]{delimiter}([^#]*){delimiter}['|\"]:\s*"` for better adaptability.

**Comment by tanchongmin** [comment]
This should be changed already in StrictJSON v3.1.0, and this fixed quite a lot of JSON bugs :)

Thank you for your inputs!
