### ISSUE TITLE
my_agent.run defaults to OPENAI even when custom LLM is passed (only if custom functions are added to agent)

### ISSUE THREAD

**Issue by ankush-ksharma** [tanchongmin/strictjson#15]
# Importance of Issue
This issue is of very high importance for the following reason
a. We are using custom LLM to save cost of calling openai.
b. The issue is only reproducible if you have NOT SET the OPENAI key.
c. If OPENAI key is set, even if I am using custom LLM, it will automatically call OPENAI for this task and the issue is NOT RAISED. So you actually send data to OPENAI even when you have your own LLM setup.

## Steps to reproduce
1. Create Custom LLM 
```
from openai import OpenAI
llm_model_name = "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"
BASE_URL = "http://192.168.10.2:1234/v1"
MAX_TOKENS = 8192

def strict_llm(system_prompt: str, user_prompt: str) -> str:
    ''' Here, we use llama3-8B '''
    # ensure your LLM imports are all within this function
    # define your own LLM here
    client = OpenAI(base_url = BASE_URL, api_key = "lm-studio")
    response = client.chat.completions.create(
        model=llm_model_name,
        temperature = 0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )
    return response.choices[0].message.content
```
2. Create a new Agent
```my_agent = Agent('Helpful assistant', 'You are a generalised agent', llm = strict_llm)```
3. Create a simple custom function (Internal or External)
```
sentence_style = Function(fn_description = "Output a sentence wtih <obj> and <entity> in the style of <emotion>",
                          outout_format = {'output':'sentence'},
                          llm = strict_llm)
 
str(sentence_style)
```
4. Assign Custom function to agent
```
my_agent.assign_function(function_list=[sentence_style])
```
5. Run the agent
```
output = my_agent.run('Give me 5 words rhying with cool, and make a 4-sentence poem using them')
```
### Error
OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
### Observation
Without the custom function the Agents works fine, but once you pass any function to agent with custom LLM, the error is raised from ranker.py
```
if self.ranking_fn is None:
     [26](.conda/envs/agents/Lib/site-packages/taskgen/ranker.py:26)     from openai import OpenAI
---> [27](.conda/envs/agents/Lib/site-packages/taskgen/ranker.py:27)     client = OpenAI()
     [28](.conda/envs/agents/Lib/site-packages/taskgen/ranker.py:28)     query_embedding = self.get_or_create_embedding(query, client)
     [29](.conda/envs/agents/Lib/site-packages/taskgen/ranker.py:29)     key_embedding = self.get_or_create_embedding(key, client)
```

## Possible Solution
Provide functionality to ranker to use custom embeddings (GPT4ALL, HUGGINGFACE) instead of defaulting to OPENAI Embeddings

**Comment by tanchongmin** [comment]
Will address this. Kindly post this Issue on the taskgen github too.

The strictjson github is mainly for LLM parsing issues.

**Comment by ankush-ksharma** [comment]
Done. Closing Issue from here.
