### ISSUE TITLE
Removing Extra Dependencies

### ISSUE THREAD

**Issue by vilsonrodrigues** [tanchongmin/strictjson#16]
Hey John, congrats for the work in StrictJSON

the project currently has dependencies that are not used (langchain, pandas, openai) is just pure python 😁

could you remove them from the project's default and make them optional via eggs?

**Comment by tanchongmin** [comment]
Thank you for the feedback. Langchain is used currently as a text splitter in memory module for TaskGen, and pandas is for the csv reading, but for the strictjson one I can remove it

openai requirement can definitely be removed, as we do not only support openai now.

I will upload a new version shortly.

**Comment by tanchongmin** [comment]
@vilsonrodrigues I have removed all dependencies except dill, termcolor, requests

actually, dill and termcolor and requests is also not used in strictjson, maybe I should remove them too

**Comment by vilsonrodrigues** [comment]
> @vilsonrodrigues I have removed all dependencies except dill, termcolor, requests
> 
> actually, dill and termcolor and requests is also not used in strictjson, maybe I should remove them too

I really appreciate your help. If possible, leaving the dependency to a minimum would be best. This helps prevent dependency conflicts. Thanks.

**Comment by tanchongmin** [comment]
@vilsonrodrigues I have removed all dependencies and added asyncio

do check if it works out for you:)

**Comment by tanchongmin** [comment]
And you can close this again if it does

**Comment by vilsonrodrigues** [comment]
> @vilsonrodrigues I have removed all dependencies and added asyncio
> 
> do check if it works out for you:)

Asyncio is built-in in Python since v3.4. The pypi version is to python 3.3

**Comment by tanchongmin** [comment]
haha means strictjson actually doesn't need any dependency

**Comment by vilsonrodrigues** [comment]
exactly, is pure python👻

**Comment by tanchongmin** [comment]
no worries, i'll just put asyncio for those who have earlier versions of python, as I kind of still want a dependency. You can close this thread if all is good for you with v5.1.2
