### ISSUE TITLE
Custom LLM Parameters

### ISSUE THREAD

**Issue by omkar-334** [tanchongmin/strictjson#18]
In base_async.py, `chat_async` function, 
```
 if llm is not None:
        ensure_awaitable(llm, 'llm')
        ''' If you specified your own LLM, then we just feed in the system and user prompt 
        LLM function should take in system prompt (str) and user prompt (str), and output a response (str) '''
        res = await llm(system_prompt = system_prompt, user_prompt = user_prompt)
```
Why are `**kwargs` not added to custom LLM (They are added to the OpenAI based LLMs).  
I suppose I could just use the OpenAI-compatible enpoint for my LLM, but this should be possible.

**Comment by tanchongmin** [comment]
You can just put the kwargs directly in the custom llm function itself, without taking it in as inputs!
