### ISSUE TITLE
usage with langchain_openai

### ISSUE THREAD

**Issue by surfingkaka** [tanchongmin/strictjson#19]
Hi, is there a way to use this with:

from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import PydanticOutputParser

parser = PydanticOutputParser(myclass)
llm = ChatOpenAI(model_name="Llama3.1")
few_shot_prompt = FewShotPromptTemplate()

chain = few_shot_prompt | llm | parser
 
chain.invoke()

**Comment by tanchongmin** [comment]
Hi there, this strictjson package is meant to replace Pydantic. Perhaps I can consider wrapping another version strictjson to use a pydantic output parser if it is more beneficial for people to do so. Then, this package will become more like Instructor package (https://github.com/instructor-ai/instructor).

Right now, I am able to get most output by just using the default Python types (e.g. str, int, list, dict) - I think using strictjson might be much more reliable than using Pydantic, but I have to do more experiments to find out.
