### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by manisense** [tanchongmin/strictjson#2]
Please update readme.md file for get started. What tech stack are pre-requisite and how to run the project.

**Comment by tanchongmin** [comment]
I have added a requirements.txt

Turns out the main thing is python version 3.11 and install openai library

**Comment by tanchongmin** [comment]
The project is also run right now as strict_text and strict_function functions.

I am in the middle of creating a python package so you can just install it using pip.

**Comment by tanchongmin** [comment]
Python package created! Hope you can use it more easily now:)
