### ISSUE TITLE
may you help to update LLM with Knowledge Graphs.ipynb 

### ISSUE THREAD

**Issue by Sandy4321** [tanchongmin/strictjson#3]
I see recent updates

but 
https://github.com/tanchongmin/TensorFlow-Implementations/blob/main/Tutorial/LLM%20with%20Knowledge%20Graphs.ipynb
works wrongly 
https://github.com/tanchongmin/TensorFlow-Implementations/issues/1

may you help to update LLM with Knowledge Graphs.ipynb

**Comment by tanchongmin** [comment]
work in progress, will update here when completed

**Comment by Sandy4321** [comment]
great thanks
hopefully will be done asap

**Comment by tanchongmin** [comment]
You're in luck! I had some free time today and updated the OpenAI API. The StrictJSON portion was actually working as it was using the old strict_output defined in the notebook.

I have updated it to use the current StrictJSON v4.0.0!

Check it out here: https://github.com/tanchongmin/strictjson/blob/main/Experiments/LLM%20with%20Knowledge%20Graphs.ipynb
